

export const NEXT_HOSTED_VALUES = ['__NEXT_REDUX_STORE__', '__NEXT_LOADED_PAGES__', '__NEXT_DATA__', '__NEXT_REGISTER_PAGE', '_N_E', '__BUILD_MANIFEST', '__BUILD_MANIFEST_CB'];

export const TY_GLOBAL_VALUES = ['__tyStoreMap', 'tyMicroApp'];

export const __REACT_ERROR_OVERLAY_GLOBAL_HOOK__ = '__REACT_ERROR_OVERLAY_GLOBAL_HOOK__';
